Repository khushi-joshi-05/Food-ordering-website, pull requests merged in 2024-07, with the labels that each got.

#1222 ADDED MORE IMAGES FOR SLIDER
  Images/homeSliderImages/home-slider-4.jpg
  Images/homeSliderImages/home-slider-5.jpg
  index.html
Labels: gssoc, level2

#1218 added offers card
  Html-files/offers.html
Labels: gssoc, level1

#1223 added hovering effect to footer
  Css-files/footer.css
  Css-files/style.css
  index.html
  style.css
Labels: gssoc, level1

#1227 Added style in contact form and get touch cards also add hover effects in scrollbar thumb
  Css-files/content.css
  Html-files/contact.html
Labels: gssoc, level2

#1250 Added Rate Us option
  Css-files/RateUs.css
  Html-files/RateUs.html
  Images/RateUs.avif
  index.html
Labels: gssoc, level2

#1251 Aligned the text in Gift Card Button and Exclusive Offers Buttons in the Service Page
  Css-files/content.css
Labels: good first issue, gssoc

#1255 Added more clients and styled the client section
  Css-files/style.css
  Html-files/MenuAPI.js
  index.html
Labels: gssoc, level2

#1257 Documentation Updated
  README.md
Labels: documentation, good first issue, gssoc, level1

#1258 added effects to image
  Css-files/login.css
  Html-files/login.html
Labels: gssoc, level1

#1262 Added PR template
  .github/pull_request_template.md
Labels: documentation, gssoc, level1

#1261 Enhance UI of FAQ Page
  index.html
  style.css
Labels: gssoc, level2

#1254 Add Signup link
  Css-files/login.css
  Html-files/login.html
  Html-files/signup.html
Labels: gssoc

#1260 Added hover for containers
  Html-files/offers.html
Labels: gssoc, level1

#1274 Added Functional "Feedback Form/Page" to the website
  Css-files/FeedbackPage.css
  Html-files/FeedbackForm.js
  Html-files/FeedbackPage.html
  index.html
Labels: enhancement, gssoc, level3

#1272 added beautiful food discount page
  Css-files/food-discount.css
  Html-files/offers/food-discount.html
  index.html
Labels: enhancement, gssoc, level3

#1278 Issue Number: # 309 Added and Updated the caraousel
  index.html
Labels: gssoc, level2

#1289 Added an option to filter according to rating.
  Html-files/MenuAPI.js
  Html-files/menu.html
Labels: enhancement, gssoc, level3

#1266 logo is added
  index.html
Labels: gssoc, level1

#1247 Fixes issue #1210
  contact-form.js
Labels: gssoc, level1

#1249 [Feature] : service page can't work Dark & Light mode
  Css-files/content.css
  Css-files/navbar.css
  Css-files/services.css
Labels: gssoc, level1

#1295 added special event page
  Css-files/special-event.css
  Html-files/offers/special-event.html
Labels: enhancement, gssoc, level3

#1297 Update RateUs.css
  Css-files/RateUs.css
Labels: gssoc, level1

#1298 Fixed the overflow of text and images on the services page.
  Html-files/offers.html
Labels: gssoc, level1

#1284 Added "Scroll Down Progress Bar" Across All Pages
  Html-files/book-table.html
  Html-files/cart.html
  Html-files/contact.html
  Html-files/login.html
  Html-files/menu.html
  Html-files/offers.html
  Html-files/services.html
  Html-files/signup.html
  Html-files/subscription.html
  contact_GSSoC_contributed.html
  index.html
Labels: gssoc, level2

#1305 Added FAQs in NAV Bar
  index.html
Labels: good first issue, gssoc, level1

#1307 fix all issues in feedback form
  Css-files/feedback.css
  Html-files/feedback.html
  Html-files/menuStars.js
Labels: gssoc, level2

#1310 Added Icons to Navbar
  Html-files/RateUs.html
  Html-files/menu.html
  index.html
Labels: gssoc, level2

#1311 Added More Sections in Menu Page
  Html-files/MenuAPI.js
Labels: documentation, good first issue, gssoc

#1306 added limited time product page
  Css-files/limited-time.css
  Html-files/offers/limited-time-products.html
Labels: gssoc

#1315 added favicon in all pages
  Html-files/FeedbackPage.html
  Html-files/RateUs.html
  Html-files/book-table.html
  Html-files/cart.html
  Html-files/cateringservices.html
  Html-files/contact.html
  Html-files/contact_GSSoC_contriburted.html
  Html-files/dish-detailes.html
  Html-files/login.html
  Html-files/menu.html
  Html-files/offers.html
  Html-files/services.html
  Html-files/signup.html
  Html-files/subscription.html
Labels: gssoc, level1

#1329 Fixed "Order online" and "Take order" icons in index.html
  Css-files/add-address.css
  Css-files/cart.css
  Html-files/add-address.html
  Html-files/address-info.js
  Html-files/cart.html
  index.html
Labels: enhancement, gssoc, level2

#1320 Highlights Card design updated
  index.html
Labels: gssoc, level2

#1323 Margin is added to each card succesfully
  Css-files/services.css
Labels: gssoc

#1338 Made the changes in the menu from $ to ₹
  Html-files/MenuAPI.js
  Html-files/dish-detailes.html
Labels: gssoc

#1317 navbar updated
  Css-files/navbar.css
  index.html
Labels: gssoc, level1

#1342 updated the "apply " and "order now" button
  Css-files/cart.css
  Html-files/cart.html
  Html-files/cart.js
  Html-files/menu.html
  cart.js
  carts.js
Labels: gssoc, level2

#1319 Beautify the Navbar with animated icons
  Css-files/navbar.css
  index.html
Labels: enhancement, gssoc, level1

#1356 contact page enhanced
  Css-files/content.css
  Html-files/contact.html
  Images/contact_page/contactpage.avif
Labels: gssoc, level1

#1361 Update PR template
  .github/pull_request_template.md
Labels: documentation, gssoc, level1

#1318 Logo
  Css-files/navbar.css
  Images/logo/Foodielogo.png
  index.html
Labels: gssoc, level1

#1362 added dark theme to entire website
  Css-files/navbar.css
  Html-files/navbar.js
  index.html
  style.css
Labels: enhancement, gssoc, level2

#1369 New Pull request template , feature template bug template and documentatiom template addition
  .github/ISSUE_TEMPLATES/bug_report.yml
  .github/ISSUE_TEMPLATES/documentation_update.yml
  .github/ISSUE_TEMPLATES/feature_request.yml
  .github/pull_request_template.md
  node_modules/.package-lock.json
Labels: documentation, gssoc, level2

#1373 ✔️ Improved "Terms and Conditions' and "Privacy Policy" Pages!
  Css-files/privacy.css
  Css-files/terms.css
  Html-files/privacy.html
  Html-files/terms.html
  index.html
Labels: documentation, gssoc, level2

#1374 made the continue shopping button work
  Html-files/cart.html
  Html-files/menu.html
Labels: gssoc, level1

#1432 Take subscription modification
  Html-files/subscription.css
Labels: gssoc

#1425 FAQ is visible now
  style.css
Labels: gssoc

#1427 Adding location [Google map] in the website
  Html-files/contact.html
  Html-files/ordertracking.html
  index.html
Labels: gssoc

#1390 logo added beside title in navbar
  Html-files/navbar.js
  Images/logo/Logo-Dark.png
  Images/logo/Logo-Light.png
  index.html
Labels: gssoc, level1

#1418 Added "Licensing page" reflecting "MIT Page"
  Html-files/Licensing.html
  index.html
Labels: gssoc

#1399 Add to cart button | Fixes issue #1115
  Css-files/content.css
Labels: gssoc

#1347 added beautifully desgin culinary experience page
  Css-files/culinary.css
  Html-files/offers/culinary-experience.html
  index.html
Labels: gssoc

#1316 Fixed Hover Color Matching in Navbar and Enhanced Navbar on Home Page
  Css-files/navbar.css
  index.html
Labels: gssoc, level1

#1468 ✔️Resolved Text-Readability Issue in Navbar
  Html-files/RateUs.html
  Html-files/contact.html
  Html-files/login.html
  Html-files/menu.html
  Html-files/offers.html
  Html-files/services.html
  Html-files/signup.html
Labels: gssoc, level1

#1360 The FAQ link in services section now correctly redirects to the FAQ section
  Html-files/services.html
  index.html
  style.css
Labels: gssoc, level2

#1489 Book Catering
  Html-files/foodcatering.html
  Html-files/services.html
Labels: gssoc

#1486 Added Visitors count
  index.html
  script.js
  style.css
Labels: gssoc

#1493 Fix incorrect URL in README
  README.md
Labels: gssoc

#1473 Fixed toogle button in nav bar.
  index.html
Labels: gssoc

#1476 ✔️ Improved the FAQ Section!
  index.html
  script.js
  style.css
Labels: gssoc

#1463 Order Online page issue
  Css-files/add-address.css
Labels: gssoc

#1492 Menu section Cards improved
  Css-files/style.css
  index.html
  style.css
Labels: gssoc

#1455 added superscript to the cart button
  Css-files/navbar.css
  Html-files/MenuAPI.js
  Html-files/menu.html
Labels: gssoc

#1440 Enhance the Cart
  Css-files/cart.css
  Html-files/MenuAPI.js
  Html-files/cart.html
  Html-files/cart.js
  carts.js
Labels: gssoc

#1442 Fix Responsiveness and Alignment Issues on Contributors Page
  Css-files/contributor.css
  Html-files/contributor.html
Labels: gssoc

#1381 Organised images
  .DS_Store
  Images/contact_page_background_image.png
  contact_GSSoC_contributed.html
  index.html
Labels: gssoc

#1351 Adding a Donate Button
  Css-files/cart.css
  Html-files/assets/donation.jpg
  Html-files/cart.html
  Html-files/cart.js
  Html-files/donation-form.html
  cartitems.js
  style.css
Labels: gssoc

#1405 Enhance navbar
  Css-files/navbar.css
  Html-files/menu.html
  Html-files/navbar.js
  index.html
  style.css
Labels: gssoc

#1450 Added scroll progress bar
  Html-files/FeedbackPage.html
  Html-files/Licensing.html
  Html-files/RateUs.html
  Html-files/add-address.html
  Html-files/cateringservices.html
  Html-files/dish-detailes.html
  Html-files/feedback.html
  Html-files/offers.html
  Html-files/privacy.html
  Html-files/terms.html
  index.html
Labels: gssoc

#1464 Vanishing Carousel Bug Fixed
  index.html
Labels: gssoc

#1485 remove underline
  Css-files/footer.css
Labels: gssoc
