Repository khushi-joshi-05/Food-ordering-website, pull requests merged in 2024-08, with the labels that each got.

#1488 Page Refresher
  Images/image.png
  index.html
  script.js
  style.css
Labels: gssoc

#1515 added homemade services
  .vscode/settings.json
  Html-files/aman.html
  Html-files/frosa.html
  Html-files/shray.html
  Images/a1.png
  Images/a2.png
  Images/a3.png
  index.html
Labels: gssoc

#1511 Navbar and path Issue#940
  Html-files/menu.html
  index.html
Labels: gssoc

#1494 Membership page
  Css-files/membership.css
  Html-files/menu.html
  Html-files/offers/membership-benifits.html
  index.html
Labels: gssoc

#1543 Fixed spelling mistake on image cards
  index.html
Labels: gssoc

#1453 Enhanced Responsiveness of Sign-Up Page Across Devices
  Css-files/RateUs.css
  Css-files/content.css
  Css-files/footer.css
  Css-files/login.css
  Css-files/offers.css
  Css-files/services1.css
  Css-files/signup.css
  index.html
Labels: gssoc, level2

#1449 Implemented Hover Effects on Menu, Services, Cart, and Contact Us Pages
  Css-files/RateUs.css
  Css-files/content.css
  Css-files/footer.css
  Css-files/login.css
  Css-files/offers.css
  Css-files/services1.css
  index.html
Labels: gssoc

#1499 improved footer and faq section
  index.html
  node_modules/.package-lock.json
  style.css
Labels: gssoc, level1

#1482 Fixed footer section for mobile screen size
  Css-files/footer.css
  Css-files/navbar.css
  index.html
Labels: gssoc, level1

#1487 GSSOC Label
  .github/workflows/auto-label-issues.yml
  .github/workflows/auto-label-pr.yml
Labels: gssoc, level1

#1523 Added New Scrollbar
  style.css
Labels: gssoc, level1

#1528 Contributor Page issue
  Css-files/contributor.css
  Html-files/contributor.html
Labels: gssoc, level2

#1545 Added Icon to FAQ
  index.html
Labels: gssoc, level1

#1553 Floating Animation to the contact section
  Css-files/content.css
  Html-files/contact.html
Labels: gssoc, level1

#1554 Navigate to the Home page from the Menu page.
  Html-files/menu.html
Labels: good first issue, gssoc

#1557 fixed css in mobile view
  Css-files/style.css
  index.html
Labels: gssoc, level1

#1558 Changes in signup file
  Html-files/signup.html
Labels: good first issue, gssoc

#1559 Added chinese food
  Html-files/MenuAPI.js
  Images/chinesefood/download (3).jpeg
  Images/chinesefood/download (4).jpeg
  Images/chinesefood/download (5).jpeg
  Images/chinesefood/download (6).jpeg
  Images/chinesefood/download (7).jpeg
  Images/chinesefood/image.png
Labels: gssoc, level1

#1549 improved the color style of the cards of offers page
  Css-files/offers.css
  Html-files/offers.html
Labels: gssoc, level1

#1564 Modified the navbar
  Css-files/navbar.css
Labels: good first issue, gssoc

#1563 FIx the Outdated Page Footer
  Html-files/contact.html
  Html-files/contact_GSSoC_contriburted.html
  Html-files/menu.html
  Html-files/nutrition.html
  Html-files/offers.html
  Html-files/ordertracking.html
  Html-files/services.html
  Html-files/shray.html
Labels: gssoc, level1

#1567 Added "Back to Home" Button and "Thank You Pop Up Message" to the feedback form
  Html-files/feedback.html
Labels: gssoc, level2

#1508 Improvement in Navbar and Improve Offers section
  Css-files/navbar.css
  Html-files/navbar.js
  Html-files/offers.html
  index.html
Labels: gssoc, level2

#1547 Added Icons to Footer
  index.html
Labels: gssoc, level1

#1560 Added Cursor Trail Effect Matching to the Website Design Theme
  Html-files/FeedbackPage.html
  Html-files/Licensing.html
  Html-files/RateUs.html
  Html-files/add-address.html
  Html-files/aman.html
  Html-files/book-table.html
  Html-files/cart.html
  Html-files/cateringservices.html
  Html-files/contact.html
  Html-files/contact_GSSoC_contriburted.html
  Html-files/contributor.html
  Html-files/dish-detailes.html
  Html-files/donation-form.html
  Html-files/feedback.html
  Html-files/foodcatering.html
  Html-files/frosa.html
  Html-files/login.html
  Html-files/menu.html
  Html-files/nutrition.html
  Html-files/offers.html
  Html-files/offers/culinary-experience.html
  Html-files/offers/food-discount.html
  Html-files/offers/limited-time-products.html
  Html-files/offers/membership-benifits.html
  Html-files/offers/special-event.html
  Html-files/ordertracking.html
  Html-files/privacy.html
  Html-files/services.html
  Html-files/shray.html
  Html-files/signup.html
  Html-files/subscription.html
  Html-files/terms.html
  contact_GSSoC_contributed.html
  index.html
Labels: gssoc, level2

#1536 theme added
  Css-files/content.css
  Css-files/navbar.css
  Css-files/offers.css
  Html-files/contact.html
  Html-files/menu.html
  Html-files/offers.html
  index.html
  script.js
Labels: gssoc, level2

#1566 Restyled the footer component
  Css-files/footer.css
  Html-files/ordertracking.html
  index.html
Labels: gssoc, level2

#1568 fixed issue 1150
  index.html
Labels: good first issue, gssoc, level1

#1572 Changed button
  Css-files/mode-toggler.css
  Html-files/navbar.js
  Images/moon.svg
  Images/sun.svg
  index.html
Labels: gssoc, level1

#1569 Food-ordering-website-mode modification
  Html-files/RateUs.html
  Html-files/cart.html
  Html-files/contact.html
  Html-files/login.html
  Html-files/menu.html
  Html-files/offers.html
  Html-files/services.html
  Html-files/signup.html
  Images/navbar/moon.png
  Images/navbar/sun.png
  index.html
  script.js
  style.css
Labels: good first issue, gssoc, level1

#1580 Added dark mode effects on the cards on the home page .
  index.html
Labels: good first issue, gssoc, level1

#1583 ✔️Implemented Dynamic "Last Updated" Functionality to All Legal Pages !
  Html-files/Licensing.html
  Html-files/privacy.html
  Html-files/terms.html
Labels: gssoc, level2

#1593 Enhanced Contact Us Page
  Css-files/content.css
  Css-files/login.css
  Html-files/contact.html
Labels: gssoc, level2

#1587 Added Vip food event
  Css-files/vip-event.css
  Html-files/offers/vip-food-event.html
  index.html
Labels: gssoc, level2

#1602 Made side menu
  Css-files/navbar.css
  Html-files/navbar.js
  index.html
Labels: gssoc, level2

#1582 Improved Offers Page
  Css-files/offers.css
  Html-files/offers.html
  style.css
Labels: gssoc, level1

#1596 Update the light and dark theme icon
  Css-files/navbar.css
  Html-files/FeedbackPage.html
  Html-files/Licensing.html
  Html-files/add-address.html
  Html-files/aman.html
  Html-files/book-table.html
  Html-files/cart.html
  Html-files/contact.html
  Html-files/foodcatering.html
  Html-files/frosa.html
  Html-files/login.html
  Html-files/menu.html
  Html-files/navbar.js
  Html-files/nutrition.js
  Html-files/offers.html
  Html-files/offers/culinary-experience.html
  Html-files/offers/food-discount.html
  Html-files/offers/limited-time-products.html
  Html-files/offers/membership-benifits.html
  Html-files/offers/special-event.html
  Html-files/privacy.html
  Html-files/services.html
  Html-files/shray.html
  Html-files/signup.html
  Html-files/terms.html
  Images/navbar/sun2.png
Labels: gssoc, level1

#1600 Removed unnecessary text on the footer section
  index.html
Labels: gssoc, level1

#1606 Made the nav-links black
  Css-files/navbar.css
  index.html
Labels: gssoc, level1

#1608 Bug fixed - Fixed the footer
  index.html
Labels: gssoc, level1

#1616 Login-Feat
  Html-files/auth.js
  Html-files/login.html
  Html-files/signup.html
Labels: gssoc, level2

#1611 Service section fixed
  index.html
Labels: gssoc, level1
