Repository khushi-joshi-05/Food-ordering-website, pull requests merged in 2024-06, with the labels that each got.

#721 Made navbar sticky
  Css-files/ContactUpdate.css
  Css-files/cart.css
  Css-files/content.css
  content/content.css
  style.css
Labels: good first issue, gssoc, level2

#744 [Fixes]: Adding a Close button #693
  Css-files/login1.css
  Css-files/signup1.css
  Html-files/login.html
  Html-files/signup.html
  style.css
Labels: good first issue, gssoc, level1

#734 the cards UI have been enhanced
  Css-files/content.css
Labels: good first issue, gssoc, level1

#707 Added new images with picture quality in contact us page
  Html-files/ContactUpdate.html
  Html-files/assets/collaboration.jpg
  Html-files/assets/discount.jpg
Labels: good first issue, gssoc, level1

#759 customer review section added
  Images/client1.jpg
  Images/client2.jpg
  Images/client3.jpg
  index.html
  style.css
Labels: enhancement, gssoc, level2

#682 Improved the UI of Contact Us Page
  Css-files/ContactUpdate.css
  Html-files/ContactUpdate.html
Labels: good first issue, gssoc, level1

#761 Changed "Bringing happiness to you" card text colour on hover
  style.css
Labels: good first issue, gssoc, level1

#775 Enhanced star rating functionality.
  Css-files/content.css
  Html-files/menu.js
Labels: gssoc, level1

#789 Redirecting to menu on clicking View our Menu on home page
  index.html
Labels: good first issue, gssoc, level1

#813 enhancing get 30% off
  style.css
Labels: gssoc, level1

#801 Changed the text colour for visibility
  .idea/.gitignore
  style.css
Labels: bug, good first issue, gssoc, level1

#825 Fix nav bar in home page
  Html-files/ContactUpdate.html
  Html-files/contact.html
  Html-files/menu.html
  Html-files/services.html
  index.html
  style.css
Labels: bug, good first issue, gssoc, level1

#829 items aligned at center in service page
  Css-files/content.css
  Html-files/services.html
Labels: gssoc, level1

#833 Fixed hover over the Contact Us Footer
  Html-files/contact.html
Labels: good first issue, gssoc, level1

#842 contact-form-popup
  Html-files/contact.html
  contact-form.js
Labels: gssoc, level1

#835 linkedin link added in footer section
  Html-files/contact.html
  Html-files/menu.html
  Html-files/services.html
  index.html
Labels: good first issue, gssoc, level1

#830 Fix Overlap Issue Between Scroll to Top Button and WebChat Bot
  Css-files/scroll-top-button.css
Labels: bug, good first issue, gssoc, level1

#840 "About Us" Text color Fixed
  index.html
Labels: duplicate, good first issue, gssoc, level1

#768 Added cateringservices page #764
  Css-files/cateringservices.css
  Html-files/cateringservices.html
  Images/birthdayImage.png
  Images/corporateimage.png
  Images/weddingimage.png
Labels: enhancement, gssoc, level2

#728 Included chatbot feature
  index.html
Labels: enhancement, gssoc, level2

#849 Replace coupen alert in the cart with nice marquee text. (fixes #637)
  Css-files/cart.css
  Html-files/cart.html
  Html-files/cart.js
Labels: gssoc, level1

#848 Make the Contact Us! form actually send the message to your mail ID. #166
  index.html
Labels: good first issue, gssoc, level1

#851 Detailed dish
  Css-files/detailed-dish.css
  Html-files/dish-detailes.html
  Html-files/menu.html
Labels: gssoc, level3

#866 Add logo to navbar
  Images/Foodielogo.png
  index.html
Labels: good first issue, gssoc

#874 Updated the UI of Contact Us page--Fixes #360
  Css-files/contact_page_background_image.png
  Css-files/content.css
  Css-files/menu.css
  Html-files/contact.html
Labels: enhancement, gssoc, level3

#886 Fix: Overflowing Layout in Subscriptions Page
  Html-files/subscription.css
Labels: good first issue, gssoc, level1

#887 Enhanced login and signup page
  Html-files/login.html
  Html-files/signup.html
Labels: good first issue, gssoc, level1

#902 Added theme colour
  .idea/Food-ordering-website.iml
  .idea/modules.xml
  .idea/vcs.xml
  index.html
  login1.css
Labels: gssoc, level1

#905 Bug: No Popup Or Alert When User Tries to login without Filling complete data #691
  Html-files/login.html
Labels: good first issue, gssoc, level1

#893 IMPROVED CSS FOR CARDS
  Css-files/ContactUpdate.css
  Html-files/ContactUpdate.html
Labels: gssoc, level1

#892 placed search bar in the webpage
  index.html
  style.css
Labels: good first issue, gssoc, level1

#912 PRE LOADER
  index.html
  style.css
Labels: gssoc, level1

#906 Page not found(services.html) - Issue resolved
  Html-files/services.html
Labels: invalid, question

#915 social media icons updated--Fixes #885
  Html-files/ContactUpdate.html
  Html-files/book-table.html
  Html-files/cart.html
  Html-files/cateringservices.html
  Html-files/contact.html
  Html-files/contact_GSSoC_contriburted.html
  Html-files/menu.html
  content/menu.html
  content/services.html
Labels: good first issue, gssoc, level1

#929 Fixed flickering issue on service page
  Css-files/services.css
  Html-files/services.html
Labels: good first issue, gssoc, level1

#933 Fixed copyright bug
  index.html
Labels: good first issue, gssoc, level1

#896 Added back to top to all sections
  Html-files/ContactUpdate.html
  Html-files/cart.html
  Html-files/contact.html
  Html-files/menu.html
  Html-files/services.html
  index.html
Labels: good first issue, gssoc, level1

#909 zoom-products menu-items
  Css-files/content.css
Labels: gssoc, level1

#938 Changed the input type for phone number
  Html-files/book-table.html
Labels: good first issue, gssoc, level1

#1009 Updated cursor to pointer in login in homepage
  Css-files/ContactUpdate.css
  Css-files/content.css
  Html-files/ContactUpdate.html
  index.html
  style.css
Labels: gssoc

#952 Want to add Backend Logic of Login/signUp page #904
  Html-files/login.html
  Html-files/signup.html
Labels: gssoc, level2

#957 #NavBar got Responsive
  style.css
Labels: gssoc, level1

#961 Fixed the size of Your message Textbox in Footer
  style.css
Labels: good first issue, gssoc

#967 Feat: Services cards animation
  Css-files/services1.css
  Html-files/services.html
Labels: gssoc, level2

#969 font changed in home page
  index.html
Labels: gssoc, level1

#979 "Contact Us" in "Offers" section is fixed
  Css-files/ContactUpdate.css
  Html-files/ContactUpdate.html
  node_modules/.package-lock.json
Labels: gssoc, level1

#993 Updated README.md
  README.md
Labels: documentation, good first issue, gssoc, level1

#1002 adding installation guide
  README.md
Labels: documentation, gssoc, level1

#1057 #added congratulation message box # Made "apply" button function
  Css-files/cart.css
  Html-files/cart.html
  Html-files/cart.js
  Images/congo-box-background.jpg
  Images/congratulation-text.jpg
  Images/order-placedsign.jpg
  Images/party-popper.jpg
  Images/social-media-symbols.png
Labels: enhancement, gssoc, level2

#1005 #947 bg color change if hovering on linedin btn in footer section
  style.css
Labels: good first issue, gssoc

#960 Dark/Light toggle button
  Css-files/style.css
  Html-files/menu.html
  Images/moon.png
  Images/sun.png
  index.html
  style.css
Labels: gssoc

#1016 Aligned Menu Headings
  Css-files/content.css
  style.css
Labels: good first issue, gssoc, level1

#1022 change the UI of footer (remove underline and better hover effect)
  index.html
  style.css
Labels: good first issue, gssoc, level1

#1023 changed the styling of the div's on the homepage
  style.css
Labels: gssoc, level1

#923 Logo For the Website issue #613
  Html-files/cateringservices.html
  Html-files/contact.html
  Html-files/dish-detailes.html
  Html-files/services.html
  Images/Foodie.png
  Images/foodie 2.png
  Images/foodie 3.png
Labels: gssoc, level1

#949 Add effect
  Html-files/cart.html
  Html-files/menu.html
  effect.css
  effect.js
  index.html
Labels: gssoc, level1

#978 update happy customer section and update it and make it responsive
  index.html
  style.css
Labels: good first issue, gssoc, level1

#986 added some effect to the image in signup page
  Css-files/signup1.css
  Html-files/signup.html
Labels: gssoc, level1

#1004 Modify the CSS of SignUp page
  Css-files/signup1.css
  Html-files/signup.html
Labels: gssoc, level1

#1025 Menu Filter Functionality #741
  Html-files/menu.html
Labels: enhancement, gssoc, level2

#1017 Navbar Elements Misaligned on Smaller Screens
  style.css
Labels: gssoc, level1

#1041 favicon added in service page
  Html-files/services.html
Labels: good first issue, gssoc, level1

#1060 Addition of Bootstrap for improving responsiveness of the website
  Css-files/cart.css
  Css-files/content.css
  Css-files/footer.css
  Css-files/navbar.css
  Css-files/offers.css
  Css-files/services.css
  Html-files/ContactUpdate.html
  Html-files/MenuAPI.js
  Html-files/cart.html
  Html-files/cateringservices.html
  Html-files/contact.html
  Html-files/dish-detailes.html
  Html-files/login.html
  Html-files/menu.html
  Html-files/menuStars.js
  Html-files/offers.html
  Html-files/services.html
  Html-files/themechange.js
  Images/Foodie_Favicon.png
  Images/app_download/download-on-the-app-store.png
  Images/app_download/get_it_on_google_play_store.png
  Images/foodie.PNG
  Images/foodie.png
  Images/homeSliderImages/home-slider-1.jpg
  Images/homeSliderImages/home-slider-2.jpg
  Images/homeSliderImages/home-slider-3.jpg
  Images/image-gallery/1.jpg
  Images/image-gallery/2.jpg
  Images/image-gallery/3.jpg
  Images/image-gallery/4.jpg
  Images/image-gallery/5.jpg
  Images/image-gallery/6.jpg
  Images/image-gallery/7.jpg
  Images/image-gallery/8.jpg
  Images/logo/Foodielogo.png
  Images/logo/sitelogo.png
  Images/testimonials/client1.jpg
  Images/testimonials/client2.jpg
  Images/testimonials/client3.jpg
  hamburger.js
  index.html
  script.js
  style.css
Labels: gssoc

#1042 Adding Home Button on Signup page
  Css-files/signup1.css
  Html-files/signup.html
Labels: gssoc, level1

#1077 signup page enhanced
  Css-files/signup1.css
  Html-files/signup.html
  Images/signupimage.jpeg
  Images/signupimage.jpg
  Images/signupimage.png
  Images/signupimg.avif
Labels: gssoc, level1

#1095 added global review card
  index.html
  style.css
Labels: gssoc, level2

#1104 Scrollbar and contact form reset fix
  Html-files/contact.html
  style.css
Labels: gssoc, level1

#1027 Enhance Feedback Section UI - Improved Visual Clarity (#806)
  index.html
Labels: gssoc, level1

#1028 Modified The Login and Sign-Up Pages
  Css-files/login1.css
  Css-files/signup1.css
  Html-files/login.html
  Html-files/signup.html
  Images/Login_burger.png
  Images/login.jpg
  Images/signbg.jpg
Labels: gssoc, level3

#975 Added Forget Password section
  Css-files/login1.css
  Html-files/forget_pass.html
  Html-files/login.html
Labels: gssoc, level2

#1069 updated index.html
  index.html
Labels: gssoc, level2

#1089 Added the preloader
  index.html
  preloader.css
  preloader.js
Labels: gssoc

#1146 Revert "Added the preloader"
  index.html
  preloader.css
  preloader.js
Labels: bug, gssoc

#1105 Added drop-down menu on services section
  index.html
  style.css
Labels: gssoc, level1

#1122 custom cursor added
  index.html
  script.js
  style.css
Labels: enhancement, gssoc, level2

#1135 FAQ Section added
  index.html
  style.css
Labels: documentation, gssoc, level1

#1149 added google translate element
  index.html
Labels: gssoc, level1

#1207 [Bug]: Add Back Button in login page and sign up page
  Css-files/login.css
  Css-files/signup.css
  Html-files/login.html
  Html-files/signup.html
Labels: gssoc, level1

#1208 Customized scrollbar
  Css-files/cart.css
  Css-files/cateringservices.css
  Css-files/content.css
  Css-files/detailed-dish.css
  Css-files/offers.css
  Css-files/services.css
  Css-files/services1.css
  Css-files/style.css
  style.css
Labels: gssoc, level1

#1211 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, gssoc, level1

#1217 Created the feedback form
  Css-files/feedback.css
  Html-files/feedback.html
  index.html
Labels: gssoc, level1

#1209 ADDED responsiveness, dark/light theme, fixed book table page #1050
  Css-files/book-table.css
  Css-files/cart.css
  Css-files/content.css
  Css-files/navbar.css
  Css-files/services.css
  Css-files/services1.css
  Html-files/book-table.html
  Html-files/cart.html
  Html-files/contact.html
  Html-files/login.html
  Html-files/menu.html
  Html-files/navbar.js
  Html-files/offers.html
  Html-files/services.html
  Html-files/signup.html
  Html-files/subscription.css
  Html-files/subscription.html
  index.html
  script.js
  style.css
Labels: gssoc, level2

#1220 Fix : Issue #390
  README.md
Labels: documentation, gssoc, level1
