Repository khushi-joshi-05/Food-ordering-website, pull requests merged in 2024-05, with the labels that each got.

#21 File Structure Optimization in Codebase
  Css-files/content.css
  Html-files/cart.html
  Html-files/contact.html
  Html-files/menu.html
  Html-files/services.html
  Images/foodie.PNG
  Images/gssoc.png
  Images/home.jpg
  Images/homepg.png
  Images/service.png
  style.css
Labels: enhancement, gssoc, level 2

#51 Adding Responsiveness & Hover Effect.
  CODE_OF_CONDUCT.md
  LICENSE
  Learn.md
  README.md
  content/cart.html
  content/contact.html
  content/content.css
  content/home.html
  content/menu.html
  content/services.html
  index.html
  style.css
Labels: enhancement, gssoc, level 1

#221 edited footer
  Html-files/contact.html
  contact.html
Labels: enhancement, gssoc

#232 fix: Order now button worked
  index.html
Labels: good first issue, gssoc

#238 fix:Placing order only when items are there
  cart.js
Labels: good first issue, gssoc

#211 make home page fully responsive
  index.html
  style.css
Labels: enhancement, gssoc, level1

#252 Create static.yml
  .github/workflows/static.yml
Labels: enhancement, gssoc

#247 changes regarding discount option
  index.html
  style.css
Labels: gssoc, level1

#267 Updated yr Fixed #218
  Html-files/cart.html
  Html-files/contact.html
  Html-files/contact_GSSoC_contriburted.html
  Html-files/menu.html
  Html-files/services.html
  contact_GSSoC_contributed.html
  content/menu.html
  content/services.html
  index.html
  style.css
Labels: good first issue, gssoc, level1

#293 Added Linkedin
  Html-files/cart.html
  Html-files/menu.html
  Html-files/services.html
  index.html
  style.css
Labels: good first issue, gssoc, level1

#306 Update index.html
  index.html
Labels: duplicate, good first issue, gssoc, level1

#365 Added more dishes in MENU (ISSUE:#298)
  Html-files/menu.html
Labels: enhancement, gssoc, level2

#375 All Links opening in current tab.(Bug Fix)
  Html-files/cart.html
  Html-files/contact.html
  Html-files/contact_GSSoC_contriburted.html
  Html-files/menu.html
  Html-files/services.html
  contact_GSSoC_contributed.html
  content/menu.html
  content/services.html
  index.html
Labels: good first issue, gssoc, level1

#387 Fixed order now button
  style.css
Labels: good first issue, gssoc, level1

#320 Solved #318
  style.css
Labels: enhancement, good first issue, gssoc, level1

#388 added footer to contact page
  Css-files/content.css
  Html-files/contact.html
Labels: enhancement, good first issue, gssoc, level2

#123 Added Favicon
  Favicon image/about.txt
  Favicon image/android-chrome-192x192.png
  Favicon image/android-chrome-512x512.png
  Favicon image/apple-touch-icon.png
  Favicon image/favicon-16x16.png
  Favicon image/favicon-32x32.png
  Favicon image/favicon.ico
  Favicon image/site.webmanifest
  index.html
Labels: enhancement, gssoc, level3

#401 footer Link update all webpage
  Html-files/cart.html
  Html-files/contact.html
  Html-files/menu.html
  Html-files/services.html
  content/menu.html
  content/services.html
  index.html
  style.css
Labels: bug, enhancement, good first issue, gssoc, level2

#402 footer Link update in landing webpage
  index.html
Labels: bug, good first issue, gssoc, level1

#241 Bug in Cart Section is fixed successfully
  cart.js
Labels: bug, gssoc, level2

#374 add hover effect on footer social media icons
  Css-files/content.css
  Html-files/menu.html
Labels: good first issue, gssoc, level1

#489 Added mini Chat bot
  index.html
Labels: gssoc, level3

#514 hide functionality added in signup page
  Css-files/signup1.css
  Html-files/scriptsignup.js
  Html-files/signup.html
Labels: gssoc, level2

#454 added go-to-top btn
  index.html
Labels: good first issue, gssoc, level1

#89 Fixed Hover effects for the site Issue
  style.css
Labels: good first issue, gssoc, level1

#525 Added Input Section For Coupon Code
  Css-files/content.css
  Html-files/cart.html
  Html-files/cart.js
Labels: enhancement, gssoc, level2

#520 Fix : Navbar Fixed
  index.html
  style.css
Labels: gssoc, level2

#544 git commit -m "Fix hover border issue and add hover effect on manu items #543"
  Css-files/content.css
  style.css
Labels: enhancement, gssoc, level1

#567 added workflow as per issue #561
  .github/workflows/autocomment-pr-raise.yml
Labels: enhancement, gssoc, level2

#559 discord and git links are added in the footer section
  Html-files/cart.html
  Html-files/contact.html
  Html-files/contact_GSSoC_contriburted.html
  Html-files/menu.html
  Html-files/services.html
  contact_GSSoC_contributed.html
  index.html
Labels: enhancement, good first issue, gssoc, level1

#566 added workflow as per issue #560
  .github/workflows/autocomment-issue.yml
Labels: enhancement, gssoc, level2

#569 text aligned in send button
  Html-files/contact.html
Labels: bug, enhancement, good first issue, gssoc, level1

#580 added workflow as per issue #565
  .github/workflows/autocomment-iss-close.yml
Labels: enhancement, gssoc, level2

#576 added workflow for old issues
  .github/workflows/close-old-issue.yml
Labels: enhancement, gssoc, level2

#577 added workflow for closing old PRs
  .github/workflows/close-old-pr.yml
Labels: enhancement, gssoc, level2

#600 Make services page responsive and add some hover effects (fixes #409)
  Css-files/services.css
  Html-files/services.html
Labels: enhancement, gssoc, level2

#591 changed the title to Foodie
  index.html
Labels: enhancement, good first issue, gssoc, level1

#605 Added hovering effects on Foot Panel
  Css-files/content.css
  Css-files/style.css
  Html-files/menu.html
  Html-files/services.html
  style.css
Labels: enhancement, good first issue, gssoc, level1

#450 [BUG] About-us section
  index.html
  style.css
Labels: enhancement, gssoc, level2

#642 Revert "[BUG] About-us section"
  index.html
  style.css
Labels: bug, gssoc

#644 Fixed text color of Cart Table
  Css-files/content.css
Labels: bug, good first issue, gssoc, level1

#645 Made Book Table page
  Css-files/content.css
  Html-files/book-table.html
  Html-files/menu.html
  index.html
Labels: enhancement, gssoc, level3

#635 Replaced Order Now with Add to Cart Button
  Html-files/menu.html
Labels: good first issue, gssoc, level1

#599 completed issue#494
  Html-files/services.html
  Html-files/subscription.css
  Html-files/subscription.html
  Images/subscription_page_bg.jpg
Labels: gssoc, level2

#627 hover effect
  style.css
Labels: enhancement, good first issue, gssoc, level1

#660 Contact US Conflict resolved #14 #532 #643
  Css-files/ContactUpdate.css
  Html-files/ContactUpdate.html
  Html-files/assets/Food-collaboration.jpg
  Html-files/assets/Food-coupons.jpg
  Html-files/assets/Food-game.jpg
  Html-files/assets/Ramen.jpg
  Html-files/assets/bruchetta.jpg
  Html-files/assets/game.png
  Html-files/assets/panipuri.jpg
  Html-files/contact.html
  Html-files/menu.html
  Html-files/services.html
  index.html
Labels: gssoc, level3

#679 Add feature to slider
  .vscode/settings.json
  hero-icon.png
  hero-slider-1.jpg
  hero-slider-2.jpg
  hero-slider-3.jpg
  index.html
  style.css
Labels: enhancement, gssoc, level2

#667 the cart footer and the items have been improved
  Css-files/cart.css
  Html-files/cart.html
Labels: bug, good first issue, gssoc, level1

#681 Sukhbir
  Css-files/ContactUpdate.css
  Css-files/cart.css
  Css-files/content.css
  Css-files/login1.css
  Css-files/menu.css
  Css-files/scroll-top-button.css
  Css-files/services.css
  Css-files/signup1.css
  Css-files/style.css
  Html-files/ContactUpdate.html
  Html-files/book-table.html
  Html-files/cart.html
  Html-files/cart.js
  Html-files/contact.html
  Html-files/contact_GSSoC_contriburted.html
  Html-files/loaderMenu.html
  Html-files/login.html
  Html-files/menu.html
  Html-files/menu.js
  Html-files/scriptlogin.js
  Html-files/scriptsignup.js
  Html-files/services.html
  Html-files/signup.html
  Html-files/subscription.css
  Html-files/subscription.html
  LICENSE
  README.md
  contact_GSSoC_contributed.html
  content/cart.html
  content/contact.html
  content/content.css
  content/home.html
  content/menu.html
  content/services.html
  hamburger.js
  index.html
  login1.css
  menu.js
  signup1.css
  style.css
Labels: enhancement, good first issue, gssoc

#703 Update README.md
  README.md
Labels: documentation, good first issue, gssoc, level1

#684 Updated social icons in footer section
  Css-files/content.css
  Html-files/menu.html
  Html-files/services.html
  index.html
  style.css
Labels: good first issue, gssoc, level1

#698 Fix:Footer-color
  style.css
Labels: good first issue, gssoc, level1

#689 footer links worked
  Html-files/menu.html
  Html-files/services.html
Labels: bug, good first issue, gssoc, level1

#715 Add dynamic copyright year script to footer
  Html-files/ContactUpdate.html
  Html-files/book-table.html
  Html-files/cart.html
  Html-files/contact.html
  Html-files/contact_GSSoC_contriburted.html
  Html-files/menu.html
  Html-files/services.html
  index.html
Labels: good first issue, gssoc, level1

#714 foodie logo updation on all web pages.
  Html-files/ContactUpdate.html
  Html-files/contact.html
  Html-files/menu.html
  Html-files/services.html
Labels: good first issue, gssoc, level1
